config/routes.rb
Foodcon::Application.routes.draw do
  devise_for :users

  root :to => 'homepage#index'
  resources :programs, :only => [:index, :show], :path => "programas"
  resources :contact_us, :only => [:index, :create, :new], :path => "contactenos" do
    collection do
      get 'gracias'
    end
  end
  resources :company_infos, :path => "informacion-de-la-compania" , :only => [:show]
  match "/admin", :controller => "admin/company_infos", :action => "index"
  namespace "admin" do
    resources :programs do
      member do
        put "update_status"
      end
    end
    resources :company_infos, :path => "informacion-compania" do
      member do
        put "update_order"
      end
    end
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  #is_sluggable :name
  has_many :program_images
  has_one :main_image
  has_one :contact_us
  accepts_nested_attributes_for :program_images
  scope :actives, where(:is_present_in_homepage => true)
#  def to_param  # overridden in order to show the name in the url
#     ("#{cached_slug}").parameterize
#  end
  
  def self.check_if_only_three_are_activated_for_homepage
    total = Program.where("is_present_in_homepage = true").count
    if total < 3
      true
    else 
      false
    end
  end
  
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < Admin::BaseController
  def index
    @programs = Program.page(params[:page]).per(10).order(:created_at)
  end
  def new
    @program = Program.new
    @program.program_images.build
  end
  def show
    @program = Program.find(params[:id])
  end
  def create
    @program = Program.new(params[:program])
    respond_to do |format|
      if @program.save
        flash[:notice] = 'Program was successfully created.'
        format.html { redirect_to admin_programs_path }
        format.xml  { head :ok }
      else
        format.html { render :new }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end 
  end
  
  def edit
    @program = Program.find(params[:id])
    @program.build_main_image
    @program.program_images.build
  end
  
  def update
    @program = Program.find(params[:id])
    respond_to do |format|
      if @program.update_attributes(params[:program])
        flash[:notice] = 'Program was successfully updated.'
          format.html { redirect_to admin_programs_path }
          format.xml  { head :ok }
      else
        format.html { render :edit }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end 
  end
  
  def destroy
    @program = Program.find(params[:id])
    @program.destroy
    respond_to do |format|
      format.html { redirect_to admin_programs_path }
      format.xml  { head :ok }
    end
  end
  
  def update_status
    @program = Program.find(params[:id])
    
    if @program.is_present_in_homepage?
      @program.is_present_in_homepage = false
      @validated = true
    else
      if Program.check_if_only_three_are_activated_for_homepage
        @program.is_present_in_homepage = true
        @validated = true
      else
        @validated = false
      end
    end
    
    respond_to do |format|
      if @validated
        @program.save
      end
      
      format.js
    end
    
    
  end
  
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  
  def show
    @program = Program.find(params[:id])
    @keywords = @program.meta_keywords
    @title = @program.name
  end
  
end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/admin/programs/_form.html.erb
<%= javascript_include_tag 'ckeditor/ckeditor' %>
<div class="form">
<p>
  <span class="req">max 100 caracteres</span>
  <label>Name <span>(Required Field)</span></label>
  <%= form.text_field :name, :class => "field size1" %>
</p>	
<p>
  <label>Meta Keywords<span>(Separados por coma.)</span></label>
  <%= form.text_area :meta_keywords, :class => "field size4" %>
</p>
<p>
  <span class="req">max 255 caracteres</span>
  <label>Short Description <span>(Homepage)</span></label>
  <%= form.text_area :short_description, :class => "field size1" %>
</p>  
<p>
  <label>Long Description</label>
  <%= form.cktext_area :description, :class => "field size4" %>
</p>	

  <%= form.fields_for :main_image do |program_image|%>
    <div class="program_image">
     <label>Main Image(609x218)</label>
      <p>
        <%= program_image.file_field :attachment %>
      </p>
    </div>
  <% end %>
 
<div class="form">
    <table>
      <tr>
        <td><label>Select layout for homepage</label></td>
        <td>&nbsp;</td>
        <td>
          1 <%= form.radio_button :type_of_layout, true %>
          2 <%= form.radio_button :type_of_layout, false %>
        </td>
      </tr>
    </table>
  
</div>


<p>
  <label>Other Images</label><%= link_to "Add Image", "javascript:void(0);", :class => "add_new_image" %>
</p>
  <%= form.fields_for :program_images do |program_image|%>
    <div class="program_image">
      <p>
        <%= program_image.file_field :attachment %>
        <% if File.exist?("#{program_image.object.attachment.path}") %>
          <%= image_tag(program_image.object.attachment.url, :width=>'75px') %>
        <% end %>
      </p>
    </div>
  <% end %>

<%#*<p class="inline-field">%>
        <%#*<label>Date</label>%>
        <%#*<select class="field size2">%>
                <%#*<option value="">23</option>%>
        <%#*</select>%>
        <%#*<select class="field size3">%>
                <%#*<option value="">July</option>%>
        <%#*</select>%>
        <%#*<select class="field size3">%>
                <%#*<option value="">2009</option>%>
        <%#*</select>%>
<%#*</p>%>

        
</div>

app/views/admin/programs/edit.html.erb
<% content_for :page_specific_javascript do %>
  <%= javascript_include_tag "admin/programs/programs.js" %>
<% end %>
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Programa
</div>
<!-- End Small Nav -->

<!-- Message Error -->
<% if @program.errors.any? %>
  <div class="msg msg-error">
     <% @program.errors.full_messages.each do |msg| %>
       <p><strong><%= msg %></strong></p>
     <% end %>
  </div>
<% end %>
<!-- End Message Error -->
<br />
<!-- Main -->
<div id="main">
        <div class="cl">&nbsp;</div>

        <!-- Content -->
        <div id="content">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2 class="left">Editar programa</h2>
            </div>
            <!-- End Box Head -->
            <%= form_for([:admin, @program]) do |f| %>
              <%= render :partial => "form", :object => f %>
              <div class="buttons">
                  <%= f.submit "Grabar" %>
                  <%= link_to "Cancelar", admin_programs_path %>
              </div>
            <% end %>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Content -->
        <!-- Sidebar -->
        <div id="sidebar">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2>Manejo</h2>
            </div>
            <!-- End Box Head-->
            <div class="box-content">
              <%= link_to(content_tag(:span, "Añadir programa"), new_admin_program_path, :class => 'add-button') %>
              <div class="cl">&nbsp;</div>
              <%= link_to(content_tag(:span, "Eliminar programa"), admin_program_path(@program), :confirm => 'Are you sure?', :method => :delete, :title => 'Delete program') %>
              
              <div class="cl">&nbsp;</div>
            </div>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Sidebar -->

        <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	

app/views/admin/programs/index.html.erb
<div class="shell">
  <!-- Small Nav -->
  <div class="small-nav">
    <a href="#">Dashboard</a>
    <span>&gt;</span>
    Programas
  </div>
  <!-- End Small Nav -->
  <br />
  <!-- Main -->
  <div id="main">
    <div class="cl">&nbsp;</div>

    <!-- Content -->
    <div id="content">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2 class="left">Programas</h2>
          <div class="right">
            <label>buscar programa</label>
            <input type="text" class="field small-field" />
            <input type="submit" class="button" value="search" />
          </div>
        </div>
        <!-- End Box Head -->	
          <!-- Table -->
          <div class="table">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th width="13">En Homepage?</th>
                <th width="110" class="ac">Content Control</th>
              </tr>
              <% @programs.each do |program| %>
                <%= content_tag_for(:tr, program, :class=> "#{cycle("", "odd")}") do %>
                  <td><h3><%= link_to program.name, admin_program_path(program) %></td>
                  <td><%= program.price %></td>
                  <td class="status" id="td_program_id_<%= program.id %>">
                   <% if program.is_present_in_homepage? %>
                    <%= link_to "activate", update_status_admin_program_path(program), :method => :put,
                       :class => 'action-activate', :title => 'Estado: Activo. Click para desactivar.', :remote => true
                    %>
                   <% else %>
                      <%= link_to "de-activate", update_status_admin_program_path(program), :method => :put,
                       :class => 'action-deactivate', :title => 'Estado: Inactivo. Click para activar.', :remote => true
                      %>
                   <% end %>
                  </td>
                  <td>
                    <%= link_to 'Borrar', admin_program_path(program), :confirm => 'Are you sure?', :method => :delete, :class => 'ico del', :title => 'Borrar programa'%>
                    <%= link_to 'Editar', edit_admin_program_path(program), :class => 'ico edit', :title => 'Editar programa' %>
                  </td>
                <% end %>
              <% end %>
            </table>

            <!-- Pagging -->
            <div class="pagging">
              <%= paginate @programs %>
            </div>
            <!-- End Pagging -->
          </div>
          <!-- Table -->
      </div>
      <!-- End Box -->
    </div>
    <!-- End Content -->

    <!-- Sidebar -->
    <div id="sidebar">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2>Manejo</h2>
        </div>
        <!-- End Box Head-->
        <div class="box-content">
          <%= link_to(content_tag(:span, "Añadir programa"), new_admin_program_path, :class => 'add-button') %>
          <div class="cl">&nbsp;</div>
          <p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
          <p><a href="#">Delete Selected</a></p>
          <!-- Sort -->
          <div class="sort">
            <label>Sort by</label>
            <select class="field">
                    <option value="">Title</option>
            </select>
            <select class="field">
                    <option value="">Date</option>
            </select>
            <select class="field">
                    <option value="">Author</option>
            </select>
          </div>
          <!-- End Sort -->
        </div>
      </div>
      <!-- End Box -->
    </div>
    <!-- End Sidebar -->

    <div class="cl">&nbsp;</div>			
  </div>
  <!-- Main -->
</div>

app/views/admin/programs/new.html.erb
<% content_for :page_specific_javascript do %>
  <%= javascript_include_tag "admin/programs/programs.js" %>
<% end %>
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Programa
</div>
<!-- End Small Nav -->

<!-- Message Error -->
<% if @program.errors.any? %>
  <div class="msg msg-error">
     <% @program.errors.full_messages.each do |msg| %>
       <p><strong><%= msg %></strong></p>
     <% end %>
  </div>
<% end %>
<!-- End Message Error -->
<br />
<!-- Main -->
<div id="main">
  <div class="cl">&nbsp;</div>

  <!-- Content -->
  <div id="content">
    <!-- Box -->
    <div class="box">
      <!-- Box Head -->
      <div class="box-head">
              <h2>Añadir nuevo prorama</h2>
      </div>
      <!-- End Box Head -->
      <%= form_for([:admin, @program]) do |f| %>
        <%= render :partial => "form", :object => f %>
        <div class="buttons">
            <%= f.submit "Grabar" %>
            <%= link_to "Cancelar", admin_programs_path %>
        </div>
      <% end %>
    </div>
    <!-- End Box -->
  </div>
  <!-- End Content -->
  <!-- Sidebar -->
  <div id="sidebar">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2>Manejo</h2>
        </div>
        <!-- End Box Head-->
        <div class="box-content">
          <%= link_to(content_tag(:span, "Añadir programa"), new_admin_program_path, :class => 'add-button') %>
          
        </div>
      </div>
      <!-- End Box -->
    </div>
  <!-- End Sidebar -->

  <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	

app/views/admin/programs/show.html.erb
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Program
</div>
<!-- End Small Nav -->

<br />
<!-- Main -->
<div id="main">
        <div class="cl">&nbsp;</div>

        <!-- Content -->
        <div id="content">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2 class="left"><%= @program.name %></h2>
              <div class="right">
                <%= link_to 'Eliminar', admin_program_path(@program), :confirm => 'Estás seguro?', :method => :delete, :class => 'ico del', :title => 'Eliminar programa'%>
                <%= link_to 'Editar', edit_admin_program_path(@program), :class => 'ico edit', :title => 'Editar programa' %>
              </div>
            </div>
            <!-- End Box Head -->
            
            <dl class="show">
          		<dt>Descripción</dt>
          		<dd><%= @program.description.html_safe %></p></dd>
          		<dt>Descripción corta (Homepage)</dt>
              <dd><%= @program.short_description %></p></dd>
          		<dt>Precio</dt>
          		<dd><%= @program.price %></p></dd>
          		<% if !@program.program_images.blank? %>
            		<dt>Image</dt>
            		<dd><%= image_tag(@program.program_images.first.attachment.url(:original), :width=>'250px') %></dd>
          		<% end %>
            </dl>
            
          </div>
          <!-- End Box -->
        </div>
        <!-- End Content -->
        <!-- Sidebar -->
        <div id="sidebar">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2>Management</h2>
            </div>
            <!-- End Box Head-->
            <div class="box-content">
              <%= link_to(content_tag(:span, "Añadir programa"), new_admin_program_path, :class => 'add-button') %>
              <div class="cl">&nbsp;</div>
            </div>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Sidebar -->

        <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	

app/views/admin/programs/update_status.js.erb
<% if @validated %>
  <% if @program.is_present_in_homepage? %>
    $("#td_program_id_<%= @program.id %>").children("a").attr("class", "action-activate");
  <% else %>
    $("#td_program_id_<%= @program.id %>").children("a").attr("class", "action-deactivate");
  <% end %>
<% else %>
    alert("Sólo pueden haber 3 programas activos en el homepage.")
<% end %>    