config/routes.rb
Foodcon::Application.routes.draw do
  devise_for :users

  root :to => 'homepage#index'
  resources :programs, :only => [:index, :show], :path => "programas"
  resources :contact_us, :only => [:index, :create, :new], :path => "contactenos" do
    collection do
      get 'gracias'
    end
  end
  resources :company_infos, :path => "informacion-de-la-compania" , :only => [:show]
  match "/admin", :controller => "admin/company_infos", :action => "index"
  namespace "admin" do
    resources :programs do
      member do
        put "update_status"
      end
    end
    resources :company_infos, :path => "informacion-compania" do
      member do
        put "update_order"
      end
    end
  end

end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  #is_sluggable :title
  has_one :company_info_image
  accepts_nested_attributes_for :company_info_image
  
#  def to_param  # overridden in order to show the name in the url
#     ("#{cached_slug}").parameterize
#  end
end

app/controllers/admin/company_infos_controller.rb
class Admin::CompanyInfosController < Admin::BaseController
  def index
    @company_infos = CompanyInfo.page(params[:page]).per(10).order(:created_at)
  end
  
  def new
    @company_info = CompanyInfo.new
    @company_info.build_company_info_image
  end
  
  def show
    @company_info = CompanyInfo.find(params[:id])
  end
  
  def create
    @company_info = CompanyInfo.new(params[:company_info])
    respond_to do |format|
      if @company_info.save
        flash[:notice] = 'CompanyInfo was successfully created.'
        format.html { redirect_to admin_company_infos_path(@company_info) }
        format.xml  { head :ok }
      else
        format.html { render :new }
        format.xml  { render :xml => @company_info.errors, :status => :unprocessable_entity }
      end
    end 
  end
  
  def edit
    @company_info = CompanyInfo.find(params[:id])
  
  end
  
  def update
    @company_info = CompanyInfo.find(params[:id])
    respond_to do |format|
      if @company_info.update_attributes(params[:company_info])
        flash[:notice] = 'CompanyInfo was successfully updated.'
          format.html { redirect_to admin_programs_path }
          format.xml  { head :ok }
      else
        format.html { render :edit }
        format.xml  { render :xml => @company_info.errors, :status => :unprocessable_entity }
      end
    end 
  end
  
  def destroy
    @company_info = CompanyInfo.find(params[:id])
    @company_info.destroy
    respond_to do |format|
      format.html { redirect_to admin_programs_path }
      format.xml  { head :ok }
    end
  end
  
  def update_status
    @company_info = CompanyInfo.find(params[:id])
    
    if @company_info.is_present_in_homepage?
      @company_info.is_present_in_homepage = false
      @validated = true
    else
      if CompanyInfo.check_if_only_three_are_activated_for_homepage
        @company_info.is_present_in_homepage = true
        @validated = true
      else
        @validated = false
      end
    end
    
    respond_to do |format|
      if @validated
        @company_info.save
      end
      
      format.js
    end
    
    
  end
end

app/controllers/company_infos_controller.rb
class CompanyInfosController < ApplicationController
  
  def show
    @company_info = CompanyInfo.find(params[:id])
    @keywords = @company_info.meta_keywords
    @title = @company_info.title
  end
  
end

app/helpers/admin/company_infos_helper.rb
module Admin::CompanyInfosHelper
end

app/helpers/company_infos_helper.rb
module CompanyInfosHelper
end

app/views/admin/company_infos/_form.html.erb
<%= javascript_include_tag 'ckeditor/ckeditor' %>
<div class="form">
<p>
  <span class="req">max 100 caracteres</span>
  <label>Título <span>(Required Field)</span></label>
  <%= form.text_field :title, :class => "field size1" %>
</p>	

<p>
  <label>Meta Keywords<span>(Separados por coma.)</span></label>
  <%= form.text_area :meta_keywords, :class => "field size4" %>
</p>

<p>
  <label>Descripción</label>
  <%= form.cktext_area :description, :class => "field size4" %>
</p>	
<p>
  <label>Imagen</label><%#= link_to "Añadir Imagen", "javascript:void(0);", :class => "add_new_tour_image" %>
</p>
  <%= form.fields_for :company_info_image do |company_info_image|%>
    <div class="tour_image">
      <p>
        <%= company_info_image.file_field :attachment %>
        <% if File.exist?("#{company_info_image.object.attachment.path}") %>
          <%= image_tag(company_info_image.object.attachment.url, :width=>'75px') %>
        <% end %>
      </p>
    </div>
  <% end %>


        
</div>

app/views/admin/company_infos/edit.html.erb
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Información
</div>
<!-- End Small Nav -->

<!-- Message Error -->
<% if @company_info.errors.any? %>
  <div class="msg msg-error">
     <% @company_info.errors.full_messages.each do |msg| %>
       <p><strong><%= msg %></strong></p>
     <% end %>
  </div>
<% end %>
<!-- End Message Error -->
<br />
<!-- Main -->
<div id="main">
        <div class="cl">&nbsp;</div>

        <!-- Content -->
        <div id="content">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2 class="left">Editar información</h2>
            </div>
            <!-- End Box Head -->
            <%= form_for([:admin, @company_info]) do |f| %>
              <%= render :partial => "form", :object => f %>
              <div class="buttons">
                  <%= f.submit "Grabar" %>
                  <%= link_to "Cancelar", admin_company_infos_path %>
              </div>
            <% end %>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Content -->
        <!-- Sidebar -->
        <div id="sidebar">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2>Manejo</h2>
            </div>
            <!-- End Box Head-->
            <div class="box-content">
              <%= link_to(content_tag(:span, "Añadir Info."), new_admin_company_info_path, :class => 'add-button') %>
              <div class="cl">&nbsp;</div>
              <%= link_to(content_tag(:span, "Eliminar Info."), admin_company_info_path(@company_info), :confirm => 'Estás Seguro?', :method => :delete, :title => 'Delete company_info') %>
              
              <div class="cl">&nbsp;</div>
            </div>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Sidebar -->

        <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	

app/views/admin/company_infos/index.html.erb
<div class="shell">
  <!-- Small Nav -->
  <div class="small-nav">
    <a href="#">Dashboard</a>
    <span>&gt;</span>
    Información de FoodCon
  </div>
  <!-- End Small Nav -->
  <br />
  <!-- Main -->
  <div id="main">
    <div class="cl">&nbsp;</div>

    <!-- Content -->
    <div id="content">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2 class="left">Información</h2>
          <div class="right">
            <label>buscar información</label>
            <input type="text" class="field small-field" />
            <input type="submit" class="button" value="search" />
          </div>
        </div>
        <!-- End Box Head -->	
          <!-- Table -->
          <div class="table">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <th>Titulo</th>
                <th width="110" class="ac">Content Control</th>
              </tr>
              <% @company_infos.each do |company_info| %>
                <%= content_tag_for(:tr, company_info, :class=> "#{cycle("", "odd")}") do %>
                  <td><h3><%= link_to company_info.title, admin_company_info_path(company_info) %></td>
                  <td>
                    <%= link_to 'Borrar', admin_company_info_path(company_info), :confirm => 'Estás seguro?', :method => :delete, :class => 'ico del', :title => 'Borrar company_infoa'%>
                    <%= link_to 'Editar', edit_admin_company_info_path(company_info), :class => 'ico edit', :title => 'Editar info.' %>
                  </td>
                <% end %>
              <% end %>
            </table>

            <!-- Pagging -->
            <div class="pagging">
              <%= paginate @company_infos %>
            </div>
            <!-- End Pagging -->
          </div>
          <!-- Table -->
      </div>
      <!-- End Box -->
    </div>
    <!-- End Content -->

    <!-- Sidebar -->
    <div id="sidebar">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2>Manejo</h2>
        </div>
        <!-- End Box Head-->
        <div class="box-content">
          <%= link_to(content_tag(:span, "Añadir Info."), new_admin_company_info_path, :class => 'add-button') %>
          <div class="cl">&nbsp;</div>
          <p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
          <p><a href="#">Delete Selected</a></p>
          <!-- Sort -->
          <div class="sort">
            <label>Sort by</label>
            <select class="field">
                    <option value="">Title</option>
            </select>
            <select class="field">
                    <option value="">Date</option>
            </select>
            <select class="field">
                    <option value="">Author</option>
            </select>
          </div>
          <!-- End Sort -->
        </div>
      </div>
      <!-- End Box -->
    </div>
    <!-- End Sidebar -->

    <div class="cl">&nbsp;</div>			
  </div>
  <!-- Main -->
</div>

app/views/admin/company_infos/new.html.erb
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Información de la Compañía
</div>
<!-- End Small Nav -->

<!-- Message Error -->
<% if @company_info.errors.any? %>
  <div class="msg msg-error">
     <% @company_info.errors.full_messages.each do |msg| %>
       <p><strong><%= msg %></strong></p>
     <% end %>
  </div>
<% end %>
<!-- End Message Error -->
<br />
<!-- Main -->
<div id="main">
  <div class="cl">&nbsp;</div>

  <!-- Content -->
  <div id="content">
    <!-- Box -->
    <div class="box">
      <!-- Box Head -->
      <div class="box-head">
        <h2>Añadir nueva información</h2>
      </div>
      <!-- End Box Head -->
      <%= form_for([:admin, @company_info]) do |f| %>
        <%= render :partial => "form", :object => f %>
        <div class="buttons">
            <%= f.submit "Grabar" %>
            <%= link_to "Cancelar", admin_company_infos_path %>
        </div>
      <% end %>
    </div>
    <!-- End Box -->
  </div>
  <!-- End Content -->
  <!-- Sidebar -->
  <div id="sidebar">
      <!-- Box -->
      <div class="box">
        <!-- Box Head -->
        <div class="box-head">
          <h2>Manejo</h2>
        </div>
        <!-- End Box Head-->
        <div class="box-content">
          <%= link_to(content_tag(:span, "Añadir Información"), new_admin_company_info_path, :class => 'add-button') %>
          
        </div>
      </div>
      <!-- End Box -->
    </div>
  <!-- End Sidebar -->

  <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	

app/views/admin/company_infos/show.html.erb
<!-- Small Nav -->
<div class="small-nav">
        <a href="#">Dashboard</a>
        <span>&gt;</span>
        Información de la Compañía
</div>
<!-- End Small Nav -->

<br />
<!-- Main -->
<div id="main">
        <div class="cl">&nbsp;</div>

        <!-- Content -->
        <div id="content">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2 class="left"><%= @company_info.title %></h2>
              <div class="right">
                <%= link_to 'Eliminar', admin_company_info_path(@company_info), :confirm => 'Estás seguro?', :method => :delete, :class => 'ico del', :title => 'Eliminar programa'%>
                <%= link_to 'Editar', edit_admin_company_info_path(@company_info), :class => 'ico edit', :title => 'Editar Info.' %>
              </div>
            </div>
            <!-- End Box Head -->
            
            <dl class="show">
          		<dt>Descripción</dt>
          		<dd><%= @company_info.description.html_safe %></p></dd>
          		<% if !@company_info.company_info_image.blank? %>
            		<dt>Image</dt>
            		<dd><%= image_tag(@company_info.company_info_image.attachment.url(:original), :width=>'250px') %></dd>
          		<% end %>
            </dl>
            
          </div>
          <!-- End Box -->
        </div>
        <!-- End Content -->
        <!-- Sidebar -->
        <div id="sidebar">
          <!-- Box -->
          <div class="box">
            <!-- Box Head -->
            <div class="box-head">
              <h2>Management</h2>
            </div>
            <!-- End Box Head-->
            <div class="box-content">
              <%= link_to(content_tag(:span, "Añadir información"), new_admin_program_path, :class => 'add-button') %>
              <div class="cl">&nbsp;</div>
            </div>
          </div>
          <!-- End Box -->
        </div>
        <!-- End Sidebar -->

        <div class="cl">&nbsp;</div>			
</div>
<!-- Main -->
	