config/routes.rb
Foodcon::Application.routes.draw do
  devise_for :users

  root :to => 'homepage#index'
  resources :programs, :only => [:index, :show], :path => "programas"
  resources :contact_us, :only => [:index, :create, :new], :path => "contactenos" do
    collection do
      get 'gracias'
    end
  end
  resources :company_infos, :path => "informacion-de-la-compania" , :only => [:show]
  match "/admin", :controller => "admin/company_infos", :action => "index"
  namespace "admin" do
    resources :programs do
      member do
        put "update_status"
      end
    end
    resources :company_infos, :path => "informacion-compania" do
      member do
        put "update_order"
      end
    end
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/company_info.rb
class CompanyInfo < ActiveRecord::Base
  #is_sluggable :title
  has_one :company_info_image
  accepts_nested_attributes_for :company_info_image
  
#  def to_param  # overridden in order to show the name in the url
#     ("#{cached_slug}").parameterize
#  end
end

app/models/company_info_image.rb
class CompanyInfoImage < Asset
  belongs_to :company_info
  validates_attachment_presence :attachment
  has_attached_file :attachment, :styles => { :mini => '48x48>', :small => '100x100>', :large => '600x600>' },
                    :default_style => :small,
                    :url => :default_program_images_url,
                    :path => :default_program_images_path
                  
  def default_program_images_url
    return "/system/uploads/:class/:id_partition/:style/:filename"
  end

  def default_program_images_path
    return ":rails_root/public/system/uploads/:class/:id_partition/:style/:filename"
  end
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base
  belongs_to :program
end

app/models/main_image.rb
class MainImage < Asset
  belongs_to :program
  validates_attachment_presence :attachment
  has_attached_file :attachment, :styles => { :mini => '48x48>', :small => '100x100>', :large => '600x600>' },
                    :default_style => :small,
                    :url => :default_program_images_url,
                    :path => :default_program_images_path
                  
  def default_program_images_url
    return "/system/uploads/:class/:id_partition/:style/:filename"
  end

  def default_program_images_path
    return ":rails_root/public/system/uploads/:class/:id_partition/:style/:filename"
  end
end

app/models/program.rb
class Program < ActiveRecord::Base
  #is_sluggable :name
  has_many :program_images
  has_one :main_image
  has_one :contact_us
  accepts_nested_attributes_for :program_images
  scope :actives, where(:is_present_in_homepage => true)
#  def to_param  # overridden in order to show the name in the url
#     ("#{cached_slug}").parameterize
#  end
  
  def self.check_if_only_three_are_activated_for_homepage
    total = Program.where("is_present_in_homepage = true").count
    if total < 3
      true
    else 
      false
    end
  end
  
end

app/models/program_image.rb
class ProgramImage < Asset
  belongs_to :program
  validates_attachment_presence :attachment
  has_attached_file :attachment, :styles => { :mini => '48x48>', :small => '100x100>', :large => '600x600>' },
                    :default_style => :small,
                    :url => :default_program_images_url,
                    :path => :default_program_images_path
                  
  def default_program_images_url
    return "/system/uploads/:class/:id_partition/:style/:filename"
  end

  def default_program_images_path
    return ":rails_root/public/system/uploads/:class/:id_partition/:style/:filename"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  prepend_before_filter :load_programs
  
  def load_programs
    @all_programs = Program.all
    @company_infos = CompanyInfo.all
    @contact_us = ContactUs.new
    @contact_us.build_program
    
  end
end

app/controllers/company_infos_controller.rb
class CompanyInfosController < ApplicationController
  
  def show
    @company_info = CompanyInfo.find(params[:id])
    @keywords = @company_info.meta_keywords
    @title = @company_info.title
  end
  
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
    @contact_us = ContactUs.new
    @contact_us.build_program
    @title = "Contáctenos"
    render :new
  end
  def new
    
  end
  
  def create
    @contact_us = ContactUs.new(params[:contact_us])
    respond_to do |format| 
      if @contact_us.save                              
        Notifier.send_information(@contact_us).deliver
        format.html { redirect_to "/" }
      else
        format.html { render :new, :locals => {:contact_us => @contact_us} }
        format.xml  { render :xml => @contact_us.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/homepage_controller.rb
# encoding: UTF-8
class HomepageController < ApplicationController
  def index
    @title = "Servicios de asesoría en Ecuador y Colombia"
    @programs = Program.actives
  end
  def mision
    @title = "Misión"
  end
  
  def vision
    @title = "Visión"
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  
  def show
    @program = Program.find(params[:id])
    @keywords = @program.meta_keywords
    @title = @program.name
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def are_you_here?(control,act=nil)
		control = control.downcase
		if act.nil?
			return control == controller.controller_name.downcase
		else
			act = act.downcase
			return (controller.controller_name.downcase == control and controller.action_name.downcase == act)
		end
	end
	
	def options_for_interests
	  programs = Program.all
    interests = Hash.new
    programs.each do |program| 
      interests[program.id] = program.name
    end
    interests[100] = "Otro"
    return interests.sort_by {|id, name| id}
  end
	
end

app/helpers/company_infos_helper.rb
module CompanyInfosHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/layouts/_admin_bar.html.erb
<!-- Header -->
<div id="header">
	<div class="shell">
		<!-- Logo + Top Nav -->
		<div id="top">
			<h1><a href="#">Foodcon Ecuador</a></h1>
			<div id="top-navigation">
				Bienvenido <strong><%= current_user.email %></strong>
				<span>|</span>
				<a href="#">Ayuda</a>
				<span>|</span>
				<a href="#">Configuración de Usuario</a>
				<span>|</span>
				<%= link_to "Log Out", destroy_user_session_path %>
			</div>
		</div>
		<!-- End Logo + Top Nav -->
		<div class="top_menu">
      <ul id="nav">
		<!-- Dashboard not being used
        <li class="top-left">
          <%#= link_to content_tag(:span, "Dashboard", {:class => "down"}), "", :class => "top_link", :id => "dashboard" %>
          <ul class="sub">
            
          </ul>
        </li>
		-->
        <li class="<%= are_you_here?("company_infos") ? "selected" : "top-left"%>">
          <%= link_to content_tag(:span, "Información de FoodCon", {:class => "down"}), "/admin", :class => "top_link", :id => "dashboard" %>
          <ul class="sub">
            
          </ul>
        </li>
        <li class="<%= are_you_here?("programs") ? "selected" : "top-middle"%>">
          <%= link_to content_tag(:span, "Programas", {:class => "down"}), admin_programs_path, :class => "top_link", :id => "dashboard" %>
        </li>
        <li class="<%= are_you_here?("tours") ? "selected" : "top-middle" %>">
          <%#= link_to content_tag(:span, "Tours", {:class => "down"}), admin_tours_path, :class => "top_link", :id => "dashboard" %>
          <ul class="sub">
            <li><%#= link_to "Last Minute", admin_tours_path(:last_minute => true) %></li>
            <li><%#= link_to "Regular Tours", admin_tours_path(:last_minute => false) %></li>
          </ul>
        </li>
		<li class="<%= are_you_here?("hotels") ? "selected" : "top-middle" %>">
          <%#= link_to content_tag(:span, "Hotels", {:class => "down"}), admin_hotels_path, :class => "top_link", :id => "dashboard" %>
        </li>
        </li>
        <li class="<%= are_you_here?("assets") ? "selected" : "top-right" %>">
          <%#= link_to content_tag(:span, "Galleries", {:class => "down"}), admin_assets_path, :class => "top_link", :id => "dashboard" %>
        </li>
		
        <!-- Clients in Phase 2
		<li class="<%= are_you_here?("clients") ? "selected" : "top-middle" %>">
          <%#= link_to content_tag(:span, "Clients", {:class => "down"}), admin_clients_path, :class => "top_link", :id => "dashboard" %>
          
        </li>
		-->
     </ul>
   </div>
		
	</div>
</div>
<!-- End Header -->

app/views/layouts/_comments.html.erb
<!-- Managed By -->
  <div class="row">
    <div class="large-12 columns">
      <div class="panel">
        <div class="row">

          <div class="large-2 small-6 columns">
            <img src="/assets/visto_bueno.png">
          </div>

          <div class="large-10 small-6 columns">
            <strong>Nuestro compromiso<hr/></strong>
            <h6 class="subheader">
              Un servicio de calidad en asesoramiento y capacitación en la industria de alimentos para su satisfacción y la de sus clientes. Su éxito es el nuestro.
            </h6>  
          </div>

        </div>
      </div>
    </div>

    <!-- End Managed By -->

app/views/layouts/_contact_us.html.erb
<div class="right_block">
          <div class="commitment">
            <img src="assets/exito.png" style="width: 150px;" />
            <p>
              Nuestro compromiso es brindarle un servicio de calidad en asesoramiento y capacitación en la industria de alimentos para su satisfacción y la de sus clientes. 
            </p>
          </div>
          <hr class="separator">
          <div>
            <p>
              Nos interesa mucho sus dudas, preguntas, comentarios y sugerencias...
            </p>
          </div><br/>
          
          
          <%= form_for([@contact_us], :url => contact_us_path) do |f| %>
            
            <%= render :partial => "contact_us/form", :object => f %>
            <div class="buttons">
                <%= f.submit "Enviar" %>
            </div>
          <% end %>
          
          
          
          <form class="contact-us">
            <img src="assets/comments-baloon.png" style="margin-right: 0px; margin-left: 110px;" />
            <div class="form-field">
              <span class="">Nombre:</span>
              <p>
              <input type="text" />
              </p>
            </div>
            <div class="form-field">
              <span class="">Email:</span>
              <p>
              <input type="text" />
              </p>
            </div>
            <div class="form-field">
              <span class="">Pais:</span>
              <p>
              <input type="text" />
              </p>
            </div>
            <div class="form-field">
              <span class="">Telefono:</span>
              <p>
              <input type="text" />
              </p>
            </div>
            <div class="form-field">
              <span class="">Mensaje:</span>
              <p>
                <textarea></textarea>
              </p>
            </div>
            <input type="submit" value="Enviar">
          </form>
          <div style="padding-top: 10px;">
            <hr class="separator">
            <p>
              En Colaboración:
            </p>
            <a href="http://www.mundohelado.com">
              <img src="assets/mundohelado.jpg" class="image-program" style="width: 180px"/>
            </a>
          </div>
        </div>



<!-- Thumbnails -->

    <div class="large-8 columns">
      <div class="row">
  <div class="large-12 columns">
          <div class="panel">
            <div class="row">

              <div class="large-2 small-6 columns">
                <img src="/assets/mail.png">
              </div>

              <div class="large-10 small-6 columns">
                <strong>Contáctenos<hr/></strong>
                  <%= form_for([@contact_us], :url => contact_us_path) do |f| %>
                    <%= render :partial => "form", :object => f %>
                    <div class="buttons">
                        <%= f.submit "Enviar" %>
                    </div>
                  <% end %>
              </div>

            </div>
          </div>
        </div>
      </div>

    <!-- End Thumbnails -->

app/views/layouts/_left_sidebar.html.erb
<div class="large-4 small-12 columns">

	<%= link_to "/" do %><img src="/assets/homepage_images/SmallLogo.jpg">
	<% end %>
	<div class="hide-for-small panel">
		<h3>Contáctenos</h3>
		<h5 class="subheader"> 
		  De Los Guayabos N51-29A <br /> y De Los Álamos <br /> Quito-Ecuador <br /> (02) 326-1442 / (09) 983-786-38 <br />
      <a href="mailto:info@foodcon.net">info@foodcon.net</a>
		</h5>
	</div>
  
	<a href="http://www.mundohelado.com">
	<div class="panel">
		<img src="/assets/mundohelado.jpg" width="240" />
	</div> </a>
  
  <div class="panel">
    <!--Facebook code -->  
    <div class="fb-like" data-href="https://www.facebook.com/pages/Food-Consulting/300068603454072?ref=ts&amp;fref=ts" data-send="false" data-width="250" data-show-faces="true"></div>
    <!-- End Facebook code -->
  </div>
 
</div>

app/views/layouts/_top_bar.html.erb
<header>
        
        	  <div class="row">
        		<div class="small-12 large-4 columns">
					<a href="/"><img src="/assets/foodcon_logo.png" height="130" /></a>
				</div>
	          </div>
	          <div class="container-carousel">
	            <div class="row carousel">
	            	<div class="small-12 large-12 columns">
	              		
	              		<!-- Jssor Slider Begin -->
						    <!-- You can move inline styles (except 'top', 'left', 'width' and 'height') to css file or css block. -->
						    <div id="slider2_container" style="position: relative; top: 0px; left: 80px; width: 500px;
						        height: 300px;">
						
						        <!-- Loading Screen -->
						        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
						            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
						                background-color: #000000; top: 0px; left: 0px;width: 100%;height:100%;">
						            </div>
						            <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;
						                top: 0px; left: 0px;width: 100%;height:100%;">
						            </div>
						        </div>
						
						        <!-- Slides Container -->
						        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 600px; height: 300px; overflow: hidden;">
						            <div>
						                <img u="image" src="/assets/comida-baja-en-grasa.jpg" />
						                <img u="thumb" src="/assets/comida-baja-en-grasa.jpg" />
						            </div>
						            <div>
						                <img u="image" src="/assets/imagen_1.png" />
						                <img u="thumb" src="/assets/imagen_1.png" />
						            </div>
						            <div>
						                <img u="image" src="/assets/imagen_2.png" />
						                <img u="thumb" src="/assets/imagen_2.png" />
						            </div>
						            <div>
						                <img u="image" src="/assets/imagen_3.png" />
						                <img u="thumb" src="/assets/imagen_3.png" />
						            </div>
						            
						        </div>
						        
						        <!-- Arrow Left -->
						        <span u="arrowleft" class="jssord02l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
						        </span>
						        <!-- Arrow Right -->
						        <span u="arrowright" class="jssord02r" style="width: 55px; height: 55px; top: 123px; right: 8px">
						        </span>
						        <!-- Direction Navigator Skin End -->
						        
						        <!-- ThumbnailNavigator Skin Begin -->
						        <div u="thumbnavigator" class="jssort03" style="position: absolute; width: 600px; height: 60px; left:0px; bottom: 0px;">
						            <div style=" background-color: #000; filter:alpha(opacity=30); opacity:.3; width: 100%; height:100%;"></div>
						
						            <div u="slides" style="cursor: move;">
						                <div u="prototype" class="p" style="POSITION: absolute; WIDTH: 62px; HEIGHT: 32px; TOP: 0; LEFT: 0;">
						                    <div class=w><ThumbnailTemplate style=" WIDTH: 100%; HEIGHT: 100%; border: none;position:absolute; TOP: 0; LEFT: 0;"></ThumbnailTemplate></div>
						                    <div class=c style="POSITION: absolute; BACKGROUND-COLOR: #000; TOP: 0; LEFT: 0">
						                    </div>
						                </div>
						            </div>
						            <!-- Thumbnail Item Skin End -->
						        </div>
						        <!-- ThumbnailNavigator Skin End -->
						        <a style="display: none" href="http://www.jssor.com">jQuery Slider</a>
						    </div>
						    <!-- Jssor Slider End -->
	              		
	              		
	              		
	              	</div>
	          	</div>
              </div>
            
          <div class="container-menu">
          	<div class="row">
          		<div class="small-12 large-12 columns">
	            <ul class="menu">
	             <li><a href="#">Inicio</a></li>
	              <li><a href="#">¿Quiénes somos?</a></li>
	              <li><a href="#">Acerca de Nosotros</a>
	                <ul>
	                  <% @company_infos.each do |company_info| %>
	                    <li>
	                      <%= link_to company_info.title, company_info_path(company_info) %>
	                    </li>
	                  <% end %>
	                </ul>
	              </li>
	              <li><a href="#">Programas</a>
	                <ul>
	                  <% @all_programs.each do |program| %>
	                    <li>
	                      <%= link_to program.name, program_path(program) %>
	                    </li>
	                  <% end %>
	                </ul>
	              </li>
	
	            </ul>
	            </div>
	          </div>
          </div>
        
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
    <meta content="<%= @keywords %>" name="keywords">
    <meta content="FoodCon asesora a su pequeño, mediano o grande negocio en l abuena práctica de manejo de alimentos." name="description">
    <!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width" />
    

  	<title>FoodCon: <%= @title %></title>
    
    <%= stylesheet_link_tag    "foundation.css" %>
    <%= stylesheet_link_tag    "style.css" %>
<%= stylesheet_link_tag    "jssorSlider.css" %>    
    
    <% if controller.controller_name == "homepage" && controller.action_name == "index" %>
      <%#= stylesheet_link_tag    "carousel.css" %>
    <% end %>
    
    <%#= javascript_include_tag "custom.modernizr.js" %>
    
		
  	<%#= csrf_meta_tags %>
  	
  </head>

  <body>
    <!--Facebook code goes here -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <!-- End Facebook code -->
    <div class="container">
      <!-- Top Bar -->
        <%= render :partial => "layouts/top_bar"%>
      <!-- End Top Bar --> 
      

      <div class="main-content">
        <div class="row">
			<div class=" large-9 columns">
	    	    <%= yield %>
	        </div>
        
			<div class=" large-3 columns">
		        <%= form_for([@contact_us], :url => contact_us_path) do |f| %>
		          <%= render :partial => "/contact_us/form", :object => f %>
		        <% end %>
	        </div>
        
        </div>
      </div>
      
     
      <footer>
        <div class="row container-footer">
				<div class=" large-5 columns">
		          <div class="footer-menu">
		            <ul>
		              <li><a href="#">Inicio</a></li>
		              <li><a href="#">Servicios</a></li>
		              <li><a href="#">Cursos</a></li>
		              <li><a href="#">Desarrollo de Productos</a></li>
		              <li><a href="#">Nosotros</a></li>
		            </ul>
		          </div>
		        </div>
				<div class=" large-3 columns">
		          <div class="contact-us">
		            <h1>Contacto</h1>
		            <div class="address">
		              <p>De los Guayabos N34-23 y Alamos · Sector Solca</p>
		              <p>Teléfonos: (00593) · 0943234567 - 345675433</p>
		              <p>e-mail: info@foodcon.net</p>
		              <p>Web: www.foodcon.net</p>
		            </div>
		          </div>
		        </div>
				<div class=" large-4 columns">
		          <div class="social-links">
		            <div class="twitter">
		              <a href="https://www.facebook.com/pages/Foodcon/300068603454072?fref=ts"><img src="assets/twitter.png"  /></a>
		            </div>
		            <div class="facebook">
		              <a href="https://www.facebook.com/pages/Foodcon/300068603454072?fref=ts"><img src="assets/facebook.png"  /></a>
		              <div class="panel">
		                <!--Facebook code -->  
		                <div class="fb-like" data-href="https://www.facebook.com/pages/Food-Consulting/300068603454072?ref=ts&amp;fref=ts" data-send="false" data-width="170" data-show-faces="true"></div>
		                <!-- End Facebook code -->
		              </div>
		            </div>
		          </div>  
        </div>
      </footer>
    </div>
    <% if Rails.env.production? %>
      <!-- ================================================================
        Google Analytics
        ============================================================== -->
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
        ga('create', 'UA-40886584-1', 'foodcon.net');
        ga('send', 'pageview');
      
      </script>
      <!-- ================================================================
        End Google Analytics
        ============================================================== -->
    <% end %>
  
  
    <%= content_for :page_specific_javascript %>
    <%= javascript_include_tag "foundation.min.js" %>
    <%= javascript_include_tag "application.js" %>
  
  <% #if controller.controller_name == "homepage" && controller.action_name == "index" %>
    
	<%= javascript_include_tag "jssor.slider.min.js" %>
	<%= javascript_include_tag "jssor.slider.mini.js" %>
	
        <script type="text/javascript">


        jQuery(document).ready(function ($) {
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 0,                               //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, default value is 3

                $ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                $SlideSpacing: 0, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, direction navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, default value is 1
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

                $DirectionNavigatorOptions: {
                    $Class: $JssorDirectionNavigator$,              //[Requried] Class to create direction navigator instance
                    $ChanceToShow: 1,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                },

                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $ActionMode: 1,                                 //[Optional] 0 None, 1 act by click, 2 act by mouse hover, 3 both, default value is 1
                    $AutoCenter: 3,                                 //[Optional] Auto center thumbnail items in the thumbnail navigator container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 3
                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange thumbnails, default value is 1
                    $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 9,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 260,                          //[Optional] The offset position to park thumbnail
                    $Orientation: 1,                                //[Optional] Orientation to arrange thumbnails, 1 horizental, 2 vertical, default value is 1
                    $DisableDrag: false                            //[Optional] Disable drag or not, default value is false
                }
            };

            var jssor_slider2 = new $JssorSlider$("slider2_container", options);
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider2.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider2.$SetScaleWidth(Math.min(parentWidth, 600));
                else
                    window.setTimeout(ScaleSlider, 30);
            }

            ScaleSlider();

            if (!navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|IEMobile)/)) {
                $(window).bind('resize', ScaleSlider);
            }
            //responsive code end
        });
    
      </script>
    <% #end %>

  </body>
</html>

app/views/notifier/send_information.html.erb
<p>
Estimado David, 
</p>    
<p>
  <%= @contact_us.full_name %> se ha contactado contigo con la siguiente información:
</p>
<p>
  <table border="0">
    <tr>
      <td>
        E-mail: 
      </td>                               
      <td><%= @contact_us.email %></td>
    </tr>
    <tr>
      <td>
        País:
      </td>                    
      <td><%= @contact_us.country %></td>
    </tr>
    <tr>
      <td>
        Ciudad:
      </td>                    
      <td><%= @contact_us.city %></td>
    </tr>
    <tr>
      <td>
        Provincia
      </td>                    
      <td><%= @contact_us.province %></td>
    </tr>
    <tr>
      <td>
        Programa:
      </td>                    
      <td>
        <% if @contact_us.program_id == 100 %>
          Otro
        <% else %>
          <%= @contact_us.program.name if !@contact_us.program.nil? %>
        <% end %>
      </td>
    </tr>                   
    <tr>
      <td>
        Su inquietud es:
      </td>                   
      <td><%= @contact_us.body %></td>
    </tr>
  </table>          
</p>